### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by sertkaya** [sisinflab-swot/cowl#2] opened 2020-01-24 10:25 UTC
I get the following compilation error:

Scanning dependencies of target cowl-shared
[  0%] Building C object CMakeFiles/cowl-shared.dir/src/io/parser/cowl_parser.c.o
In file included from /home/xxx/workspace/cowl/src/io/parser/cowl_parser.c:13:0:
/home/xxx/workspace/cowl/src/io/parser/cowl_parser.c: In function ‘cowl_parser_parse_ontology’:
/home/xxx/workspace/cowl/build/flex_bison/cowl_functional_lexer.h:114:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘->’ token
 #define yyin yyg->yyin_r

**Comment by IvanoBilenchi** [comment] 2020-01-24 10:45
Looks like an error in the generated lexer. Which versions of Flex and Bison are you using? I may try to reproduce this, and either find a fix or bump the minimum required version of either tool.

FYI, it seems to build fine with the latest versions of Flex and Bison (2.6.4 and 3.5.1, respectively).

**Comment by sertkaya** [comment] 2020-01-24 10:48
Thanks. cmake says the following:

-- Found BISON: /usr/bin/bison (found suitable version "3.0.4", minimum required is "3.0") 
-- Found FLEX: /usr/bin/flex (found suitable version "2.6.1", minimum required is "2.6") 
-- Desktop build selected
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen missing components: dot
-- Failed to find sphinx-build (missing: SPHINX_EXECUTABLE)

**Comment by IvanoBilenchi** [comment] 2020-01-24 11:16
Alright so the culprit seems to be Flex: I tried downgrading to version 2.6.1 and it indeed causes compilation errors. Bison 3.0.4 is fine, so the 3.0+ requirement is ok. Mind trying to upgrade Flex to 2.6.4?

Let me know if that works, in which case I'll bump the minimum required version of the tool.

**Comment by IvanoBilenchi** [comment] 2020-01-29 13:40
Fixed in 0420325579388bccd277845a11f4bb4eba25ff2d.

Feel free to comment if upgrading Flex does not solve your issue.

**Closed by IvanoBilenchi** 2020-01-29 13:40 UTC
Labels: bug
