### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [sisinflab-swot/cowl#3] opened 2020-03-24 16:42 UTC
Would you like to add more error handling for return values from functions like the following?
- [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [cowl_logger_close](https://github.com/sisinflab-swot/cowl/blob/d7201b7f5cc59361b37af3f3bf2266198d784da8/src/io/cowl_logger.c#L41)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [cowl_string_alloc](https://github.com/sisinflab-swot/cowl/blob/7ec18d7a079bf0945503289060afe7af82b77bf8/src/model/cowl_string.c#L28)

**Comment by IvanoBilenchi** [comment] 2020-03-25 10:20
Oof, the missed fclose checks are an oversight on my end. I will fix them shortly.

As for malloc, I currently follow the (sub-optimal) strategy to ignore failed allocator calls. This is only temporary though, as support for custom allocators and allocator failure strategies is on my to-do list.

**Comment by elfring** [comment] 2020-03-25 13:37
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by IvanoBilenchi** [comment] 2020-04-25 08:12
Even though this appears to be a spambot, the issue is a real one and it was addressed [in the latest commits](https://github.com/sisinflab-swot/cowl/compare/67886ab...de57410).

Closing and locking conversation to avoid further spam.

**Closed by IvanoBilenchi** 2020-04-25 08:12 UTC
Labels: enhancement
